name: Instagram Reel Automation

on:
  schedule:
    # This workflow runs daily at 06:00 UTC (adjust the cron schedule if needed)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  post_reel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib schedule requests

      # Decode and write Google Drive credentials from secret (if provided)
      - name: Set up Google Drive credentials
        if: env.GOOGLE_DRIVE_CREDENTIALS_BASE64 != ''
        run: |
          echo "$GOOGLE_DRIVE_CREDENTIALS_BASE64" | base64 -d > credentials.json
        env:
          GOOGLE_DRIVE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS_BASE64 }}

      - name: Run automation script
        env:
          INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
        run: |
          python auto_post.py
